"""make_document_id_nullable

Revision ID: 10f4acad51b1
Revises: 8f64a8670b44
Create Date: 2026-02-13 10:15:11.206853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f4acad51b1'
down_revision: Union[str, Sequence[str], None] = '8f64a8670b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
